// episode3/react-app/src/App.tsx
import React, { Component, ChangeEvent } from 'react';
import Person from './component/Person';
import './App.scss';

class App extends Component<{}, any> {

  newPersonName: string = '';
  constructor(props: any) {
    super(props);
    this.state = {
      inputValue: '',
      persons: ['Ragnar', 'Lagertha']
    }
  }

  change = (event: ChangeEvent<HTMLInputElement>) => {
    this.setState({
      inputValue: event.target.value
    })
  }

  addPerson(name: string){
    this.setState((state: any) =>{
      const persons = state.persons.concat(name);
      return {
        persons
      }
    })
  }

  render() {
    return (
      <Layout></Layout>
    )
  };
}

export default App;

// episode2/angular-app/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class AppComponent {

  persons: string[] = ['Ragnar', 'Lagertha'];
  inputValue: string = '';

  change = (event: ChangeEvent<HTMLInputElement>) => {
    this.setState({
      inputValue: event.target.value
    })
  }

  addPerson(name: string){
    this.setState((state: any) =>{
      const persons = state.persons.concat(name);
      return {
        persons,
        inputValue: ''
      }
    })
  }

  removePerson = (i: number) => {
    this.setState((state: any) => {
      const newArray = state.persons.slice();
      newArray.splice(i, 1);
      return {
        persons: newArray
      }
    })
  }

}

<div class="App">
  <h1>React vs Angular</h1>
  <div class="input-container">
    <label>name</label>
    <input id="name" type="text" />
  </div>
  <div class="persons-list">
    <app-person *ngFor="let name of persons" [name]="name" ></app-person>
  </div>
</div>
